name: ci-cd

on: [ push ]

jobs:
  run_tests_and_lint:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install poetry
        run: pip install poetry
      
      - name: Install tox
        run: pip install tox

      - name: Install package
        run: poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

      - name: Do linting
        run: tox run -e lint

      - name: Run all tests
        run: tox
